site_name: EMPOP
theme: readthedocs

nav:
- Introduction: empop_use.md
- Concept: 
- Register:
  - LogIn: 
- Searches:
  - Query Options: 
  - Results:
  - Details:
  - Neighbors:
  - Alignment:
  - Haplogrouping:
- FAQ:
- Contact:

repo_name: gmitirol/empop-use
repo_url: https://github.com/gmitirol/empop-use
