site_name: EMPOP Documentation
theme: readthedocs

nav:
- Home: index.md
- Revision Overview: revisions.md
- Introduction: introduction.md
- Concept: concept.md
- Register & Login: register.md
- Using EMPOP for mitotype searches: using_empop.md
- Browsing EMPOP for populations: browsing_empop.md
- EMPOP Tools: tools.md

markdown_extensions:
  - admonition

plugins:
  - search
  - git-revision-date-localized
